### ISSUE TITLE
Make proximo-server a library

### ISSUE THREAD

**Issue by thesyncim** [uw-labs/proximo#12]
hi nice project!

I would be nice to turn the server into a library and export "handler" interface so new Backends can be added without hacking.

**Comment by mjgarton** [comment]
Thanks for the contribution.

Can you explain further what you mean by "hacking" here please?

Looking at this another way, previous backends have been added in the past without a problem.  What problem does this solve?

**Comment by thesyncim** [comment]
I mean that i need to clone this repo and edit the content of proximo-server in order to add a new backend. 
With this PR you can just import and implement Handler interface.

**Comment by SpeedyCoder** [comment]
this has been done in https://github.com/uw-labs/proximo/pull/73
