### ISSUE TITLE
Add NSQ backend

### ISSUE THREAD

**Issue by thesyncim** [uw-labs/proximo#15]
more info http://nsq.io/

I have a PR ready with this functionality but it was build on top of #13

**Comment by mjgarton** [comment]
NSQ does not (as far as I know) guarantee ordering, making it unsuitable for the target uses of proximo.

Perhaps this target use needs clarifying more explicitly in the README.

**Comment by mjgarton** [comment]
https://github.com/uw-labs/proximo/issues/21

**Comment by thesyncim** [comment]
Sry for the noise here!
you are right!
Alternative we can use [this ](https://github.com/youzan/nsq) fork

**Comment by mjgarton** [comment]
I appreciate the contributions, but I think this should wait until we have a concrete use case for this, especially if it depends on a NSQ fork.

Thanks for the contribution, but I'm going to close this until we have a real use case needing this.
